[phase.setup]
aptPkgs = ['wget']

[phases.install]
dependsOn = ['setup']
cmds = ['wget https://smlnj.org/dist/working/110.95/config.tgz', 'tar -xzf config.tgz', 'config/install.sh -default 64']

[start]
cmd = "gunicorn grader:app"
