[phases.install]
cmds = ['export LC_ALL=C', 'curl -O http://smlnj.cs.uchicago.edu/dist/working/110.99.7.1/config.tgz', 'tar -xzf config.tgz', 'config/install.sh']

[start]
cmd = "gunicorn grader:app"
